export const TRANSLATIONS = {
  ar: {
    appName: "صلاتي نور",
    prayerTimes: "أوقات الصلاة",
    qibla: "القبلة",
    tracker: "المتتبع",
    prayerTracker: "متتبع الصلوات",
    adhkar: "الأذكار",
    settings: "الإعدادات",
    nextPrayer: "الصلاة القادمة",
    fajr: "الفجر",
    sunrise: "الشروق",
    dhuhr: "الظهر",
    asr: "العصر",
    maghrib: "المغرب",
    isha: "العشاء",
    language: "اللغة",
    arabic: "العربية",
    english: "English",
    markAsDone: "سجل صلواتك",
    addNote: "إضافة ملاحظة",
    reflections: "تأملات",
    consistency: "الالتزام",
    morningAdhkar: "أذكار الصباح",
    eveningAdhkar: "أذكار المساء",
    myDuas: "أدعيتي",
    addDua: "إضافة دعاء",
    favorite: "المفضلة",
    qiblaGuide: "وجه هاتفك نحو الكعبة المشرفة",
    vibrationEnabled: "الاهتزاز عند القبلة",
    save: "حفظ",
    cancel: "إلغاء",
  },
  en: {
    appName: "Salati Noor",
    prayerTimes: "Prayer Times",
    qibla: "Qibla",
    tracker: "Tracker",
    prayerTracker: "Prayer Tracker",
    adhkar: "Adhkar",
    settings: "Settings",
    nextPrayer: "Next Prayer",
    fajr: "Fajr",
    sunrise: "Sunrise",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    language: "Language",
    arabic: "العربية",
    english: "English",
    markAsDone: "Track Prayers",
    addNote: "Add Note",
    reflections: "Reflections",
    consistency: "Consistency",
    morningAdhkar: "Morning Adhkar",
    eveningAdhkar: "Evening Adhkar",
    myDuas: "My Du'as",
    addDua: "Add Du'a",
    favorite: "Favorites",
    qiblaGuide: "Point your phone towards the Kaaba",
    vibrationEnabled: "Vibrate at Qibla",
    save: "Save",
    cancel: "Cancel",
  }
};

export const ADHKAR_DATA = {
  morning: [
    { id: 'm1', text: "أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.", count: 1 },
    { id: 'm2', text: "اللهم بك أصبحنا، وبك أمسينا، وبك نحيا، وبك نموت، وإليك النشور.", count: 1 },
    { id: 'm3', text: "رضيت بالله رباً، وبالإسلام ديناً، وبمحمد صلى الله عليه وسلم نبياً.", count: 3 },
  ],
  evening: [
    { id: 'e1', text: "أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.", count: 1 },
    { id: 'e2', text: "اللهم بك أمسينا، وبك أصبحنا، وبك نحيا، وبك نموت، وإليك المصير.", count: 1 },
    { id: 'e3', text: "أعوذ بكلمات الله التامات من شر ما خلق.", count: 3 },
  ]
};
